### ISSUE TITLE
🚀 [Feature] 관리자페이지 - AdminApprovalInfo, AdminReportInfo 페이지 작업과 기능 구현

### ISSUE THREAD

**Issue by from1to2** [coffee-meet/frontend#106]
## 🚀 어떤 기능을 만드나요?
- AdminApprovalInfo, AdminReportInfo 페이지 작업
- AdminApprovalInfo, AdminReportInfo 모달창 적용
## 작업 중인 브랜치
feat/AdminInfo
## ☑ Implement TODO
- [x] AdminApprovalInfo, AdminReportInfo 페이지 작업 
- [x] AdminApprovalInfo, AdminReportInfo 모달창 적용
- [x] 리스트 클릭 시, 해당 '이름'의 AdminApprovalInfo, AdminReportInfo 정보  보여주기
- [x] AdminTabs 적용
- [x] input placeholder 위치 뒤로 당기기. box-sizing, padding 해결
- [ ] 뒤로가기 버튼 , Admin tabs 클릭 유지 -> 상위 컴포넌트에서 tabClicked 상태관리가 필요할 듯하다 🤔  (추가 사항), 처음 구조 설계의 문제? 전역 상태관리의 필요성

**Comment by wukdddang** [comment]
https://github.com/prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF/tree/main/src/context
Tab은 잘 해결해가고 있으신가요?? 참고하실만한 코드 남겨드려요
